name: pointer
train:
    batch_size: 128
    LOAD_EPOCH:
    epochs: 6
    num_workers: 6
    eval_period: 1
    checkpoint_period: 1
    device: cuda
    lr: 0.001
    lr_decay: 0.6
    clip_value: 5
model:
    hidden_size: 800
    embedding_sizeT: 512
    embedding_sizeN: 300
    dropout: 0
    num_layers: 1
    label_smoothing: 0
    pointer: True
    attn: True
data:
    truncate_size: 50
    N_filename: ./pickle_data/PY_non_terminal_small.pickle
    T_filename: ./pickle_data/PY_terminal_10k_whole.pickle
